
#####

GET http://localhost:5000/ HTTP/1.1

######
GET http://localhost:5000/company/get-companies HTTP/1.1

###
POST http://localhost:5000/company/add-company HTTP/1.1
Content-Type: application/json

{
    "name":"atia",
    "password":"atia222",
    "email":"atiaa@dfsdf.dfd",
    "adress":"hehia"
}
###
POST https://insurance-sys.herokuapp.com/company/add-company HTTP/1.1
Content-Type: application/json

{
    "name":"atia",
    "password":"atia222",
    "email":"atiaa@dfsdf.dfd",
    "adress":"hehia"

}
####

GET http://localhost:5000/company/get-company/13 HTTP/1.1

###
POST http://localhost:5000/program/add-program HTTP/1.1
Content-Type: application/json

{
    "program_name":"ca",
    "max_balance":"50000",
    "company_id":"13"
}